name: Update Heatmap

on:
  schedule:
    - cron: '0 4 * * *' # tous les jours à 04:00 UTC donc 06:00 / 05:00 en France (UTC+2 / UTC+1)
  workflow_dispatch: # permet de lancer manuellement

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.GITLAB_TOKEN_TO_GET_STAT }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install dependencies
        run: pip install requests matplotlib numpy

      - name: Run heatmap script
        run: python generate_heatmap.py

      - name: Commit and push SVG
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
