name: Update Heatmap

on:
  schedule:
    - cron: '0 4 * * *' # tous les jours à 04:00 UTC
  workflow_dispatch: # permet de lancer manuellement

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.GITLAB_TOKEN_TO_GET_STAT }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # important pour permettre le push

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install requests matplotlib numpy

      - name: Run heatmap script
        run: python generate_heatmap.py

      - name: Show git diff before commit
        run: |
          git status
          git diff --stat

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add gitlab_heatmap.svg
          git commit -m "Auto update heatmap $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
